Repository stepflow-ai/stepflow, pull requests merged in 2025-07, with the labels that each got.

#138 feat: Support `.` and `[...]` in paths
  .github/workflows/pr.yml
  CLAUDE.md
  schemas/flow.json
  sdks/python/src/stepflow_sdk/generated_flow.py
  stepflow-rs/crates/stepflow-analysis/src/dependency.rs
  stepflow-rs/crates/stepflow-analysis/src/validation.rs
  stepflow-rs/crates/stepflow-core/src/values/value_ref.rs
  stepflow-rs/crates/stepflow-core/src/values/value_resolver.rs
  stepflow-rs/crates/stepflow-core/src/values/value_template.rs
  stepflow-rs/crates/stepflow-core/src/workflow.rs
  stepflow-rs/crates/stepflow-core/src/workflow/expr.rs
  stepflow-rs/crates/stepflow-core/src/workflow/json_path.rs
Labels: core, py

#141 docs: Update for json path expression support
  docs/docs/getting_started.md
Labels: docs

#140 chore: Fix python lints & mypy
  .github/actions/python-checks/action.yml
  schemas/flow.json
  sdks/python/pyproject.toml
  sdks/python/src/stepflow_sdk/context.py
  sdks/python/src/stepflow_sdk/exceptions.py
  sdks/python/src/stepflow_sdk/flow_builder.py
  sdks/python/src/stepflow_sdk/generated_flow.py
  sdks/python/src/stepflow_sdk/generated_protocol.py
  sdks/python/src/stepflow_sdk/message_decoder.py
  sdks/python/src/stepflow_sdk/server.py
  sdks/python/src/stepflow_sdk/udf.py
  sdks/python/src/stepflow_sdk/value.py
  sdks/python/tests/test_flow_builder.py
  sdks/python/tests/test_json_encoding.py
  sdks/python/tests/test_message_decoder.py
  sdks/python/tests/test_server.py
  sdks/python/tests/test_value.py
  sdks/python/uv.lock
  stepflow-rs/crates/stepflow-core/src/workflow/flow.rs
Labels: core, py

#143 refactor: Replace PluginError with strongly-typed McpError variant
  docs/docs/components/index.md
  stepflow-rs/Cargo.lock
  stepflow-rs/crates/stepflow-components-mcp/Cargo.toml
  stepflow-rs/crates/stepflow-components-mcp/src/error.rs
  stepflow-rs/crates/stepflow-components-mcp/src/plugin.rs
Labels: core, docs

#148 feat: Allow substitutions in environment variables
  CLAUDE.md
  docs/docs/runtime/config.md
  stepflow-rs/Cargo.lock
  stepflow-rs/Cargo.toml
  stepflow-rs/README.md
  stepflow-rs/crates/stepflow-components-mcp/Cargo.toml
  stepflow-rs/crates/stepflow-components-mcp/src/plugin.rs
  stepflow-rs/crates/stepflow-protocol/Cargo.toml
  stepflow-rs/crates/stepflow-protocol/src/error.rs
  stepflow-rs/crates/stepflow-protocol/src/plugin.rs
  stepflow-rs/crates/stepflow-protocol/src/stdio/launcher.rs
Labels: core, docs

#150 refactor: move tests from stepflow-rs to top-level
  scripts/test-integration.sh
  stepflow-rs/crates/stepflow-main/tests/commands/mod.rs
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_run__run_basic_workflow_with_file_input.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_run__run_basic_workflow_with_json_input.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_run__run_basic_workflow_with_yaml_input.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_run__run_invalid_input_json.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_run__run_with_custom_config.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_submit__submit_connection_error.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_submit__submit_with_file_input.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_test__test_basic_workflow.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_test__test_mock_directory.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_test__test_with_custom_config.snap
  stepflow-rs/crates/stepflow-main/tests/commands/test_list_components.rs
  stepflow-rs/crates/stepflow-main/tests/commands/test_run.rs
  stepflow-rs/crates/stepflow-main/tests/commands/test_submit.rs
  tests/basic.yaml
  tests/builtins/blob_test.yaml
  tests/builtins/nested_eval.yaml
  tests/builtins/stepflow-config.yml
  tests/mcp/basic_mcp.yaml
  tests/mcp/stepflow-config.yml
  tests/mock/basic.yaml
  tests/mock/conditional_skip.yaml
  tests/mock/conditional_skip_use_default.yaml
  tests/mock/error_fail.yaml
  tests/mock/error_skip.yaml
  tests/mock/error_use_default.yaml
  tests/mock/error_use_default_value.yaml
  tests/mock/input.json
  tests/mock/stepflow-config.yml
  tests/no_tests.yaml
  tests/python/blob_integration.yaml
  tests/python/blob_simple.yaml
  tests/python/stepflow-config.yml
  tests/python/udf_function.yaml
  tests/python/udf_simple.yaml
  tests/python/udf_text_processing.yaml
  tests/sql-state/simple_workflow.yaml
  tests/sql-state/stepflow-config.yml
  tests/stepflow-config.yml
Labels: core

#158 refactor: Eliminate unsafe blocks for env tests
  stepflow-rs/Cargo.toml
  stepflow-rs/crates/stepflow-components-mcp/src/plugin.rs
  stepflow-rs/crates/stepflow-protocol/src/stdio/launcher.rs
  stepflow-rs/crates/stepflow-protocol/src/stdio/recv_message_loop.rs
Labels: core

#162 refactor: Update typscript SDK for new schema location. Bring up to d…
  sdks/typescript/README.md
  sdks/typescript/src/index.ts
  sdks/typescript/src/main.ts
  sdks/typescript/src/protocol.ts
  sdks/typescript/src/server.ts
  sdks/typescript/src/transport.ts
  sdks/typescript/tests/server.test.ts
Labels: ts

#163 feat: Add UDF support to typescript SDK.
  sdks/typescript/package.json
  sdks/typescript/src/index.ts
  sdks/typescript/src/main.ts
  sdks/typescript/src/udf.ts
  sdks/typescript/tests/udf.test.ts
Labels: ts

#164 feat: Added HTTP Server Mode to typescript SDK for feature parity with python
  sdks/typescript/README.md
  sdks/typescript/examples/http-server-demo.ts
  sdks/typescript/package.json
  sdks/typescript/src/cli.ts
  sdks/typescript/src/http-server.ts
  sdks/typescript/src/index.ts
  sdks/typescript/src/main.ts
  sdks/typescript/src/server.ts
  sdks/typescript/src/transport.ts
  sdks/typescript/tests/http-server.test.ts
  sdks/typescript/tests/server.test.ts
Labels: ts

#165 feat: Adds flow building API for programatic flows
  sdks/typescript/src/flow-builder.ts
  sdks/typescript/src/index.ts
  sdks/typescript/src/value.ts
  sdks/typescript/tests/flow-builder.test.ts
  sdks/typescript/tests/value.test.ts
Labels: ts

#167 docs: Add comprehensive examples for SDK features, update README for …
  sdks/typescript/README.md
  sdks/typescript/examples/complete-component-server.ts
  sdks/typescript/examples/flow-builder-comprehensive.ts
  sdks/typescript/examples/udf-examples.ts
  sdks/typescript/examples/value-system-showcase.ts
Labels: ts

#170 refactor: update config to camel case consistently
  CLAUDE.md
  README.md
  docs/docs/examples/custom-components.md
  docs/docs/runtime/config.md
  docs/docs/workflows/best-practices.md
  docs/docs/workflows/testing.md
  examples/eval/README.md
  examples/mcp-component/README.md
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_list_components__list_components_format_json.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_list_components__list_components_format_yaml.snap
  stepflow-rs/crates/stepflow-main/tests/commands/snapshots/test_cli__commands__test_list_components__list_components_json_no_schemas.snap
  stepflow-rs/crates/stepflow-main/tests/commands/test_list_components.rs
  stepflow-rs/crates/stepflow-plugin/src/routing/rules.rs
  tests/http/stepflow-config.yml
Labels: core, docs

#172 refactor: Rename stepflow-sdk to stepflow-py
  CLAUDE.md
  README.md
  docs/docs/examples/custom-components.md
  docs/docs/protocol/transport.mdx
  docs/docs/runtime/config.md
  examples/basic/stepflow-config.yml
  examples/custom-python-components/README.md
  examples/custom-python-components/custom_server.py
  examples/data-pipeline/stepflow-config.yml
  examples/eval/README.md
  examples/eval/stepflow-config.yml
  examples/file-loading/stepflow-config.yml
  examples/loop-components/loop_server.py
  load-tests/workflows/message_custom_server.py
  load-tests/workflows/openai_custom_server.py
  load-tests/workflows/stepflow-config.yml
  load-tests/workflows/stepflow-standalone-config.yml
  sdks/python/README.md
  sdks/python/examples/session_example.py
  sdks/python/generate.py
  sdks/python/pyproject.toml
  sdks/python/src/stepflow_py/__init__.py
  sdks/python/src/stepflow_py/context.py
  sdks/python/src/stepflow_py/exceptions.py
  sdks/python/src/stepflow_py/flow_builder.py
  sdks/python/src/stepflow_py/generated_protocol.py
  sdks/python/src/stepflow_py/http_server.py
  sdks/python/src/stepflow_py/main.py
  sdks/python/src/stepflow_py/message_decoder.py
  sdks/python/src/stepflow_py/py.typed
  sdks/python/src/stepflow_py/server.py
  sdks/python/src/stepflow_py/stdio_server.py
  sdks/python/src/stepflow_py/udf.py
  sdks/python/src/stepflow_py/value.py
  sdks/python/tests/test_flow_builder.py
  sdks/python/tests/test_http_server.py
  sdks/python/tests/test_json_encoding.py
  sdks/python/tests/test_message_decoder.py
  sdks/python/tests/test_server.py
  sdks/python/tests/test_stdio_server.py
  sdks/python/tests/test_value.py
  sdks/python/uv.lock
  sdks/typescript/README.md
  sdks/typescript/package.json
  sdks/typescript/src/cli.ts
  stepflow-rs/crates/stepflow-protocol/tests/test_echo_server.py
  tests/http/test_python_server.py
  tests/python/stepflow-config.yml
Labels: core, py, ts, docs

#173 ci: Update release process for python
  .github/workflows/release_dispatch.yml
  .github/workflows/release_prepare.yml
  .github/workflows/release_python.yml
  RELEASE.md
  scripts/prepare-release-python.sh
  scripts/prepare-release-rust.sh
  sdks/python/cliff.toml
Labels: py

#184 fix: Notification responses
  examples/custom-python-components/README.md
  examples/custom-python-components/custom_server.py
  schemas/protocol.json
  sdks/python/src/stepflow_py/generated_protocol.py
  sdks/python/src/stepflow_py/http_server.py
  sdks/python/src/stepflow_py/server.py
  sdks/python/src/stepflow_py/stdio_server.py
  sdks/python/tests/test_json_encoding.py
  sdks/python/tests/test_message_decoder.py
  sdks/python/tests/test_server.py
  sdks/python/tests/test_stdio_server.py
  sdks/typescript/src/http-server.ts
  sdks/typescript/src/protocol.ts
  sdks/typescript/src/server.ts
  stepflow-rs/crates/stepflow-builtins/src/plugin.rs
  stepflow-rs/crates/stepflow-components-mcp/src/plugin.rs
  stepflow-rs/crates/stepflow-components-mcp/tests/integration_test.rs
  stepflow-rs/crates/stepflow-main/src/args/workflow.rs
  stepflow-rs/crates/stepflow-main/src/stepflow_config.rs
  stepflow-rs/crates/stepflow-mock/src/mock_plugin.rs
  stepflow-rs/crates/stepflow-plugin/src/plugin.rs
  stepflow-rs/crates/stepflow-protocol/src/plugin.rs
  stepflow-rs/crates/stepflow-protocol/src/protocol/initialization.rs
  stepflow-rs/crates/stepflow-protocol/tests/http_integration_test.rs
  stepflow-rs/crates/stepflow-protocol/tests/test_echo_server.py
  stepflow-rs/scripts/prepare-release.sh
  tests/http/test_python_server.py
Labels: core, py, ts

#185 fix: registration of UDF component
  sdks/python/src/stepflow_py/main.py
  sdks/python/src/stepflow_py/server.py
  sdks/python/tests/test_http_server.py
  sdks/python/tests/test_server.py
Labels: py

#188 fix: Enable attribute access in UDFs
  sdks/python/pyproject.toml
  sdks/python/src/stepflow_py/udf.py
  sdks/python/tests/test_udf.py
  sdks/python/uv.lock
Labels: py

#190 fix(py): decorator should preserve iscoroutine property
  sdks/python/src/stepflow_py/__init__.py
  sdks/python/src/stepflow_py/server.py
  sdks/python/tests/test_server.py
Labels: py

#191 chore: add response logging
  sdks/python/src/stepflow_py/udf.py
  stepflow-rs/crates/stepflow-protocol/src/http/bidirectional_driver.rs
  stepflow-rs/crates/stepflow-protocol/src/http/client.rs
Labels: core, py
